### ISSUE TITLE
Using Bifrost after the video is cropped

### ISSUE THREAD

**Issue by TbtBI** [dubhater/vapoursynth-bifrost#1]
Hi. Is there a requirement to use Bifrost before cropping the video? There is green line at the bottom when Bifrost is applied on already cropped video.

```
FFVideoSource("source.mkv")
Bifrost()
```
The result is [this](http://imgbox.com/RhWABxV).
Sample [here](https://www.upload.ee/files/9860486/source.mkv.html).
Vapoursynth version has the same behavior.

**Comment by dubhater** [comment]
Cropping is only a problem because Bifrost doesn't process the leftover pixels at the bottom when the height isn't a multiple of the block height. It's a bug in Bifrost.

**Comment by TbtBI** [comment]
Is a fix expected or better using version 1.1 for such scenarios?

**Comment by dubhater** [comment]
I'm not expecting a fix anytime soon.

**Comment by TbtBI** [comment]
Thanks for the reply.

I guess this ticket can be closed.
