### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Selur** [dubhater/vapoursynth-bifrost#4]
From the looks of it, bifrost does not properly free the memory when unloaded, see: https://github.com/YomikoR/VapourSynth-Editor/issues/55

**Comment by dubhater** [comment]
Could be.

**Comment by myrsloik** [comment]
https://github.com/dubhater/vapoursynth-bifrost/blob/master/src/bifrost.c#L643 <- args is only freed when interlaced=True but always allocated.
Move freemap a few lines down outside the if statement I guess?

**Comment by Selur** [comment]
@myrsloik : Thanks for looking at it.

**Comment by dubhater** [comment]
@myrsloik Sounds good!

**Comment by Selur** [comment]
@dubhater : would be nice if you could make a new release with this. Thanks!

**Comment by dubhater** [comment]
I don't have a suitable compiler anymore...

**Comment by myrsloik** [comment]
Give me access and I'll do it+convert it to api4?

**Comment by myrsloik** [comment]
A build to test. I hopefully didn't create any new leaks with the API4 changes.
https://www.dropbox.com/scl/fi/7iv172ltfrfertva531lk/bifrost-test2.7z?rlkey=scam4h8fy5yk0iq2qcrcy15by&dl=1

**Comment by Selur** [comment]
Yes, that build fixes the memory issue for me!
